# Generated by Django 4.2.7 on 2023-11-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0.0, max_length=5),
        ),
    ]
