# Generated by Django 4.2.5 on 2023-11-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_game_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamid',
            field=models.IntegerField(default=0),
        ),
    ]
